services:
  # Aplikasi Web (Nginx)
  web:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./config:/app/config # Mapping folder config dari repo ke container
      - /var/run/docker.sock:/var/run/docker.sock:ro # Agar bisa baca status docker lain
    networks:
      - app_network
    # Healthcheck untuk memastikan nginx siap sebelum ngrok connect
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Ngrok Tunnel (Pintu ke Internet)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: production_tunnel
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=parthenogenetically-proequality-rebbeca.ngrok-free.dev" # GANTI DENGAN DOMAIN ANDA
      - "web:80" # Mengarah ke service 'web' port 80
      #2yRXYkYRabv6V5jn6idf8vuPkrt_Gk6LsFk4gpH7aPQt5tPE
    networks:
      - app_network
    depends_on:
      web:
        condition: service_healthy
    
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: monitoring
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - "3001:3001" # Akses via IP Lokal Proxmox (Internal)
    networks:
      - app_network

volumes:
  uptime-kuma-data:

networks:
  app_network:
    driver: bridge