services:
  # Aplikasi Web (Homepage)
  web:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1000:1000"
    restart: unless-stopped
    # Tambahkan environment ID agar file config tidak dikunci root
    environment:
      - PUID=1000 # ID user runner (cek dengan mengetik `id` di terminal runner, biasanya 1001 atau 1000)
      - PGID=1000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network
    # HEALTHCHECK WAJIB ADA karena ngrok depends_on service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ngrok Tunnel
  ngrok:
    image: ngrok/ngrok:latest
    container_name: production_tunnel
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=parthenogenetically-proequality-rebbeca.ngrok-free.dev"
      - "--host-header=localhost:3000"  # <--- GANTI 'rewrite' JADI INI
      - "--basic-auth=admin:zinus" # <--- TAMBAHKAN BARIS INI
      - "web:3000"
    networks:
      - app_network
    depends_on:
      web:
        condition: service_healthy
#ss
  # Monitoring (Opsional)
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: monitoring
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    networks:
      - app_network

volumes:
  uptime-kuma-data:

networks:
  app_network:
    driver: bridge