services:
  web:
    # ... (service nginx yang lama biarkan saja)

  ngrok:
    image: ngrok/ngrok:latest
    container_name: production_tunnel
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=https://parthenogenetically-proequality-rebbeca.ngrok-free.dev"
      - "web:80"
    networks:
      - app_network
    depends_on:
      web:
        condition: service_healthy

  # Tambahkan Service Baru: Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: monitoring
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - "3001:3001" # Akses via IP Lokal Proxmox (Internal)
    networks:
      - app_network

volumes:
  uptime-kuma-data:

networks:
  app_network:
    driver: bridge