---
# Group pertama: Favorit
- My First Group:
    - Google:
        icon: google.png
        href: https://google.com
        description: Search Engine

# Group kedua: DevOps Monitoring
- Infrastructure:
    - Uptime Kuma:
        icon: uptime-kuma.png
        # Kita belum mengekspos port 3001 ke internet, jadi href ini mungkin belum bisa diklik dari luar
        # Tapi widget di bawah ini AKAN jalan karena komunikasi antar container (internal network)
        href: http://localhost:3001 
        description: Monitoring Server
        widget:
          type: uptimekuma
          url: http://monitoring:3001 # Menggunakan nama container "monitoring"
          slug: default # Kita perlu config ini nanti di Uptime Kuma, biarkan dulu