---
- My Infrastructure:
    - Proxmox:
        icon: proxmox.png # Otomatis mengambil logo Proxmox
        href: https://10.62.8.242:8006 # Ganti IP Proxmox Anda
        description: Virtualization Server

    - Docker Portainer:
        icon: portainer.png
        href: http://10.62.9.53:9000 # Contoh jika ada portainer
        description: Container Manager

- Monitoring:
    - Uptime Kuma:
        # Perhatikan: icon 'uptimekuma' (tanpa spasi/dash biasanya works, atau cek dokumentasi)
        icon: uptime-kuma.png 
        href: http://10.62.9.53:3001
        widget:
          type: uptimekuma
          url: http://10.62.9.53:3001
          slug: myweb