---
title: Dashboard DevOps Saya
background:
  # Anda bisa pakai URL gambar dari internet (Unsplash) atau upload file ke folder images
  image: https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop
  brightness: 50 # Gelapkan background 50% agar teks terbaca

header: true # Tampilkan header (pencarian, info sistem)
layout:
  My First Group:
    style: row
    columns: 4